// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgKsawcUMqmGAgtQFcfv1XaWjxDNoM_lY',
    appId: '1:1037406951755:web:7be8e6f33b78d8eab530ce',
    messagingSenderId: '1037406951755',
    projectId: 'emobility0001-ef8f4',
    authDomain: 'emobility0001-ef8f4.firebaseapp.com',
    databaseURL: 'https://emobility0001-ef8f4-default-rtdb.firebaseio.com',
    storageBucket: 'emobility0001-ef8f4.firebasestorage.app',
    measurementId: 'G-DJQGS8WQ1D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDykWuXfLXp-K7nY-UUJuxpv550sNbUPeI',
    appId: '1:1037406951755:android:45316400fa5d8ac3b530ce',
    messagingSenderId: '1037406951755',
    projectId: 'emobility0001-ef8f4',
    databaseURL: 'https://emobility0001-ef8f4-default-rtdb.firebaseio.com',
    storageBucket: 'emobility0001-ef8f4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcHEOyVXRHxIBsz9ajCiKtAGpgYHLNG0I',
    appId: '1:1037406951755:ios:cee7ada74be8ef32b530ce',
    messagingSenderId: '1037406951755',
    projectId: 'emobility0001-ef8f4',
    databaseURL: 'https://emobility0001-ef8f4-default-rtdb.firebaseio.com',
    storageBucket: 'emobility0001-ef8f4.firebasestorage.app',
    iosBundleId: 'com.example.batteryMonitor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcHEOyVXRHxIBsz9ajCiKtAGpgYHLNG0I',
    appId: '1:1037406951755:ios:cee7ada74be8ef32b530ce',
    messagingSenderId: '1037406951755',
    projectId: 'emobility0001-ef8f4',
    databaseURL: 'https://emobility0001-ef8f4-default-rtdb.firebaseio.com',
    storageBucket: 'emobility0001-ef8f4.firebasestorage.app',
    iosBundleId: 'com.example.batteryMonitor',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4Y8daMg5BlGHssAI1iobIBgARnY5HWVQ',
    appId: '1:1037406951755:web:7117a383f8afb72cb530ce',
    messagingSenderId: '1037406951755',
    projectId: 'emobility0001-ef8f4',
    authDomain: 'emobility0001-ef8f4.firebaseapp.com',
    databaseURL: 'https://emobility0001-ef8f4-default-rtdb.firebaseio.com',
    storageBucket: 'emobility0001-ef8f4.firebasestorage.app',
    measurementId: 'G-R4YL2863L4',
  );
}
